server:
  httpListenAddr: ':3592'
  grpcListenAddr: ':3593'

storage:
  driver: disk
  disk:
    directory: /policies
    watchForChanges: true

audit:
  enabled: true
  accessLogsEnabled: true
  decisionLogsEnabled: true
  backend: local
  local:
    storagePath: /var/log/cerbos
    retentionPeriod: 168h
